### <b> Course: Machine Learning for Absolute Beginners - Level 2
#### By: Idan Gabrieli
####  Exercise #2 – Pandas Series and DataFrame
*****************************

### Step 1 - Series Data Structure (1D)

Create a series data structure called s1 with the following values [10,20,30,40,50,60] and then print it.

In [2]:
import pandas as pd
s1 = pd.Series([10,20,30,40,50,60])
s1

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

Print the left column which is the index.

In [4]:
ix = s1.index
print(ix)

RangeIndex(start=0, stop=6, step=1)

Print the type of the second column which is the actual data.

In [5]:
s1.dtype

dtype('int64')

Print the values in index location 3.

In [6]:
s1[3]

40

Create a series data structure called s2 with the following values [10,20,30,40,50,60] and with index ['a', 'b', 'c', 'd', 'e', 'f'] then print it.

In [7]:
s2=pd.Series([10,20,30,40,50,60],index=['a','b','c','d','e','f'])
s2

a    10
b    20
c    30
d    40
e    50
f    60
dtype: int64

Print the value in row with the index label 'e'.

In [8]:
s2['e']

50

Change the value of row with the index label 'e' into 51.

In [9]:
s2['e']=51

Print all rows between labels 'b' and 'e' using the slice notation.

In [10]:
s2['b':'e']

b    20
c    30
d    40
e    51
dtype: int64

Print all rows between labels 'b' until the end using the slice notation.

In [11]:
s2['b':]

b    20
c    30
d    40
e    51
f    60
dtype: int64

Add the number 3 to all rows in s2 without using a for-loop.

In [13]:
s2 = s2+3
s2

a    16
b    26
c    36
d    46
e    57
f    66
dtype: int64

Check if the value 54 is in s2 without using a for-loop.

In [14]:
54 in s2

False

Check which values in s2 are greater than 30.

In [16]:
s2>30

a    False
b    False
c     True
d     True
e     True
f     True
dtype: bool

Print the values in s2 that are greater than 30.

In [17]:
s2[s2>30]

c    36
d    46
e    57
f    66
dtype: int64

print all values in s2 that are greater than the mean value.

In [19]:
s2[s2>s2.mean()]

d    46
e    57
f    66
dtype: int64

### Step 2 - DataFrame Data Structure (2D)

Create a dictionary called dic1 with the following data: {'Name':[ 'David', 'John', 'Marta', 'Dianna'], 'Age':[41,19,33,24],'Weight':[85,76,67,56]} and then create create a dataframe called df from dic1. Print df dataframe.

In [21]:
dic1 = {'Name':[ 'David', 'John', 'Marta', 'Dianna'], 'Age':[41,19,33,24],'Weight':[85,76,67,56]}
df = pd.DataFrame(dic1)
df

     Name  Age  Weight
0   David   41      85
1    John   19      76
2   Marta   33      67
3  Dianna   24      56

Print the rows index attribute of df dataframe.

In [22]:
df.index

RangeIndex(start=0, stop=4, step=1)

Print the columns attribute of df dataframe.

In [23]:
df.columns

Index(['Name', 'Age', 'Weight'], dtype='object')

Print the values attribute of df dataframe.

In [24]:
df.values

array([['David', 41, 85],
       ['John', 19, 76],
       ['Marta', 33, 67],
       ['Dianna', 24, 56]], dtype=object)

Bonus step - can you change the rows index attribute to the following labels: 'R1', 'R2', 'R3', 'R4' and print the df dataframe? (tip - create a list with those new labels and then copy the list into the relevant dataframe attribute).

In [25]:
df.reindex(['R1','R2','R3','R4'])

   Name  Age  Weight
R1  NaN  NaN     NaN
R2  NaN  NaN     NaN
R3  NaN  NaN     NaN
R4  NaN  NaN     NaN

### Step 3 - Data Selection in a DataFrame

Create a dictionary called dic1 with the following data: {'Name':[ 'David', 'John', 'Marta', 'Dianna'], 'Age':[41,19,33,24],'Weight':[85,76,67,56]} and then create create a dataframe called df from dic1 with the following rows index ['a','b','c','d']. Print the dataframe.

In [26]:
dic1 = {'Name':[ 'David', 'John', 'Marta', 'Dianna'], 'Age':[41,19,33,24],'Weight':[85,76,67,56]}
df = pd.DataFrame(dic1,index=['a','b','c','d'])
df

     Name  Age  Weight
a   David   41      85
b    John   19      76
c   Marta   33      67
d  Dianna   24      56

Print the 'Name' column using the dot notation.

In [27]:
df.Name

a     David
b      John
c     Marta
d    Dianna
Name: Name, dtype: object

Print the 'Name' and 'Age' columns using square brackets.

In [28]:
df[['Name','Age']]

     Name  Age
a   David   41
b    John   19
c   Marta   33
d  Dianna   24

Print the type of object returned by selecting the 'Name' column using square brackets.

In [29]:
type(df['Name'])

pandas.core.series.Series

Print the type of object returned by selecting the 'Name' and 'Age' columns using square brackets.

In [30]:
type(df[['Name','Age']])

pandas.core.frame.DataFrame

Print the rows starting in index location 0 and ending in index location 2.

In [31]:
print(df[0:2])

    Name  Age  Weight
a  David   41      85
b   John   19      76

Print all rows with columns 'Name' and 'Age' while using the loc method.

In [36]:
df.loc[:,['Name','Age']]

     Name  Age
a   David   41
b    John   19
c   Marta   33
d  Dianna   24

Print rows  with labels 'a' and 'd' with columns 'Name' and 'Age' while using the loc method.

In [37]:
df.loc[['a','d'],['Name','Age']]

     Name  Age
a   David   41
d  Dianna   24

Print the row in index location 2 using the iloc method.

In [39]:
df.iloc[[2]]

    Name  Age  Weight
c  Marta   33      67

Print the rows in index location 1,2 and 3 using the iloc method.

In [40]:
df.iloc[[1,2,3]]

     Name  Age  Weight
b    John   19      76
c   Marta   33      67
d  Dianna   24      56

Print the rows in index location 1,2 and 3 and columns in index locations 0 to 1 using the iloc method.

In [41]:
df.iloc[[1,2,3],[0,1]]

     Name  Age
b    John   19
c   Marta   33
d  Dianna   24

### End of document
************************