In [1]:
import pandas as pd

In [2]:
s1 = pd.Series([2,4,6,8,10])#creating a series
s1

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [3]:
s1.index#accessing index of the series

RangeIndex(start=0, stop=5, step=1)

In [4]:
s1.dtype#reading the data type of the second column in the series

dtype('int64')

In [5]:
s1[0]#accessing the data in second column of the series

2

In [6]:
s2 = pd.Series([5,10,15,20],index=['a','b','c','d'])#Using characters for index
s2

a     5
b    10
c    15
d    20
dtype: int64

In [7]:
s2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [8]:
s2['a']=7#changing the value at an index
s2

a     7
b    10
c    15
d    20
dtype: int64

In [9]:
s2['b':'d']#index slicing

b    10
c    15
d    20
dtype: int64

In [10]:
#Need of pandas series instead of lists -> Math operations
list1 = [2,4,6,8,10]
list2 = list1 + list1#instead of adding the individual elements in list, appending occurs
print(list2)
s3 = s1 + s1 #Adding two pandas series
s3#Mathematical operations can be performed with pandas series in an intuitive manner without any for loops

[2, 4, 6, 8, 10, 2, 4, 6, 8, 10]

0     4
1     8
2    12
3    16
4    20
dtype: int64

In [11]:
#Options similar to matlab logical indexing is possible with pandas
filt = s2>10
print(filt)
print(s2[filt])
print(s2[s2>s2.mean()])#Using mean method with logical indexing

a    False
b    False
c     True
d     True
dtype: bool
c    15
d    20
dtype: int64
c    15
d    20
dtype: int64

In [12]:
#Creating a big series with same number
s3 = pd.Series(5,index=range(0,100))
s3

0     5
1     5
2     5
3     5
4     5
     ..
95    5
96    5
97    5
98    5
99    5
Length: 100, dtype: int64

In [13]:
#Creating a pandas series from a dictionary
profile = {'Id':123,'Name': 'abc','Age':35,'Role':'xyz'}
s4 = pd.Series(profile,name='Info')#key of dictionary is used as index, value of dice is used as values, name is used to mention meta data(optional)
s4

Id      123
Name    abc
Age      35
Role    xyz
Name: Info, dtype: object

In [14]:
#Creating a dataframe(2D tables) from dictionary
#Each column of the table is a pandas series
bio_dict = {'Name':['abc','def','ghi'], 'Age':[25,27,32], 'Id':[123,456,789]}
d1 = pd.DataFrame(bio_dict,index=['a','b','c'])
print(d1)
print(d1.index)
print(d1.columns)

  Name  Age   Id
a  abc   25  123
b  def   27  456
c  ghi   32  789
Index(['a', 'b', 'c'], dtype='object')
Index(['Name', 'Age', 'Id'], dtype='object')

In [15]:
#accessing data from data frame
print(d1.Name)#accessing a column
print(d1['Name'])#accessing a column
print(d1[0:2])#accessing rows -> slicing is mandatory otherwise python thinks we are accessing columns and will lead to error
print(d1['Age'][0:1])#accessing subset of dataframe
print(d1.loc[['a'],['Name','Id']])#accessing subset using loc method. Characters based location selection.
print(d1.iloc[[1,2],[0,1]])#accessing subset using iloc method. Index based location selection.

a    abc
b    def
c    ghi
Name: Name, dtype: object
a    abc
b    def
c    ghi
Name: Name, dtype: object
  Name  Age   Id
a  abc   25  123
b  def   27  456
a    25
Name: Age, dtype: int64
  Name   Id
a  abc  123
  Name  Age
b  def   27
c  ghi   32

In [16]:
d2 = d1[d1['Age']>30]#Conditional filtering
d2

  Name  Age   Id
c  ghi   32  789

In [17]:
t_df = pd.read_csv("titanic.csv")#importing csv as a data frame
t_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [18]:
t_df.head(10)#displaying first 10 rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [19]:
#While importing csv using pandas use pd.read_csv("filename.csv",header = None) if column name is not present in first line. Pandas would assign numbers as column names. Use prefix arg to
#combine numbers with a string. Example pd.read_csv("filename.csv",header=None,prefix="col-") would generate column names as col-1 col-2 and so on.
#Column names can also be provided manually using a list like pd.read_csv("filename.csv",header=None or 0(to overwrite existing names at first line),names=column_names_list)

In [20]:
t_nameindex_df = pd.read_csv("titanic.csv", header = 0, index_col=3)#using Name as row index
t_nameindex_df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
"Montvila, Rev. Juozas",887,0,2,male,27.0,0,0,211536,13.0000,NaN,S
"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,B42,S
"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.0000,C148,C
"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [21]:
t_specificCols_df = pd.read_csv("titanic.csv",header=0,usecols=[0,1,2,3,4])
t_specificCols_df

,PassengerId,Survived,Pclass,Name,Sex
0,1,0,3,"Braund, Mr. Owen Harris",male
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female
2,3,1,3,"Heikkinen, Miss. Laina",female
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female
4,5,0,3,"Allen, Mr. William Henry",male
...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male
887,888,1,1,"Graham, Miss. Margaret Edith",female
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female
889,890,1,1,"Behr, Mr. Karl Howell",male
890,891,0,3,"Dooley, Mr. Patrick",male

In [22]:
t_df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [23]:
t_dtypemod_df = pd.read_csv("titanic.csv",header=0,dtype={"Survived":"bool"})#Changing datatype of column during import
t_dtypemod_df.dtypes

PassengerId      int64
Survived          bool
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [24]:
t_df.shape#Getting the number of rows and columns

(891, 12)

In [25]:
t_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [26]:
t_df.count()#Gives the number of proper values in each column

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [27]:
t_df['Sex'].unique()#Gives the unique values of that column

array(['male', 'female'], dtype=object)

In [28]:
t_df['Embarked'].value_counts()#Gives the count of each unique value in the column

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [29]:
t_df['Sex'].value_counts(normalize=True)#To get percentage of each unique value

male      0.647587
female    0.352413
Name: Sex, dtype: float64

In [30]:
#Statistics of a column
print(t_df['Age'].min())
print(t_df['Age'].max())
print(t_df['Age'].mean())
print(t_df[['Age','Fare']].mean())#Mean of multiple columns
print(t_df.max())#Max of all columns
print(t_df['Survived'].sum())

0.42
80.0
29.69911764705882
Age     29.699118
Fare    32.204208
dtype: float64
PassengerId                            891
Survived                                 1
Pclass                                   3
Name           van Melkebeke, Mr. Philemon
Sex                                   male
Age                                   80.0
SibSp                                    8
Parch                                    6
Ticket                           WE/P 5735
Fare                              512.3292
dtype: object
342

C:\Users\dit1cob\AppData\Local\Temp/ipykernel_33992/3330594684.py:6: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print(t_df.max())#Max of all columns

In [31]:
#What is the max age of 80% of all passengers?
t_df.quantile(0.8)

PassengerId    713.0000
Survived         1.0000
Pclass           3.0000
Age             41.0000
SibSp            1.0000
Parch            1.0000
Fare            39.6875
Name: 0.8, dtype: float64

In [32]:
#Summary of the data
t_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [33]:
#Method chaining
t_df.isnull().sum()#Counting number of null values in each column

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [34]:
#Calculating the mean age of all non null values in age column
t_df.dropna()['Age'].mean()

35.6744262295082

In [35]:
#sorting
t_df.sort_values('Age',ascending=False).head(10)#First 10 highest age sort

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q

In [36]:
t_df.sort_values('Age',ascending=False)[['Name','Age']].head(10)#Filtering only name and age

                                     Name   Age
630  Barkworth, Mr. Algernon Henry Wilson  80.0
851                   Svensson, Mr. Johan  74.0
493               Artagaveytia, Mr. Ramon  71.0
96              Goldschmidt, Mr. George B  71.0
116                  Connors, Mr. Patrick  70.5
672           Mitchell, Mr. Henry Michael  70.0
745          Crosby, Capt. Edward Gifford  70.0
33                  Wheadon, Mr. Edward H  66.0
54         Ostby, Mr. Engelhart Cornelius  65.0
280                      Duane, Mr. Frank  65.0

In [37]:
t_df.dropna().sort_values(['Sex','Age'],ascending=[True,False])[['Sex','Name','Age']]

        Sex                                              Name    Age
275  female                 Andrews, Miss. Kornelia Theodosia  63.00
366  female  Warren, Mrs. Frank Manley (Anna Sophia Atkinson)  60.00
11   female                          Bonnell, Miss. Elizabeth  58.00
195  female                              Lurette, Miss. Elise  58.00
268  female     Graham, Mrs. William Thompson (Edith Junkins)  58.00
..      ...                                               ...    ...
445    male                         Dodge, Master. Washington   4.00
193    male                        Navratil, Master. Michel M   3.00
340    male                    Navratil, Master. Edmond Roger   2.00
183    male                         Becker, Master. Richard F   1.00
305    male                    Allison, Master. Hudson Trevor   0.92

[183 rows x 3 columns]

In [38]:
t_df.nlargest(10,'Age')[['Name','Age']]

                                     Name   Age
630  Barkworth, Mr. Algernon Henry Wilson  80.0
851                   Svensson, Mr. Johan  74.0
96              Goldschmidt, Mr. George B  71.0
493               Artagaveytia, Mr. Ramon  71.0
116                  Connors, Mr. Patrick  70.5
672           Mitchell, Mr. Henry Michael  70.0
745          Crosby, Capt. Edward Gifford  70.0
33                  Wheadon, Mr. Edward H  66.0
54         Ostby, Mr. Engelhart Cornelius  65.0
280                      Duane, Mr. Frank  65.0

In [39]:
t_df.nsmallest(10,'Age')[['Name','Age']]

                                Name   Age
803  Thomas, Master. Assad Alexander  0.42
755        Hamalainen, Master. Viljo  0.67
469    Baclini, Miss. Helene Barbara  0.75
644           Baclini, Miss. Eugenie  0.75
78     Caldwell, Master. Alden Gates  0.83
831  Richards, Master. George Sibley  0.83
305   Allison, Master. Hudson Trevor  0.92
164     Panula, Master. Eino Viljami  1.00
172     Johnson, Miss. Eleanor Ileen  1.00
183        Becker, Master. Richard F  1.00

In [41]:
#Filtering
t_df[t_df["Sex"]=="female"]#Filtering only female passengers

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [42]:
t_df[t_df['Age']>60]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S
252,253,0,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S
275,276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
545,546,0,1,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,NaN,S
555,556,0,1,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
625,626,0,1,"Sutton, Mr. Frederick",male,61.0,0,0,36963,32.3208,D50,S
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [44]:
t_df[(t_df['Sex']=='female') & (t_df['Age']>60)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
275,276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN

In [45]:
condition = (t_df['Sex']=='female') & (t_df['Age']>60)
t_df.loc[condition,['Name','Sex','Age']]

                                          Name     Sex   Age
275          Andrews, Miss. Kornelia Theodosia  female  63.0
483                     Turkula, Mrs. (Hedwig)  female  63.0
829  Stone, Mrs. George Nelson (Martha Evelyn)  female  62.0

In [46]:
#Grouping and aggregation
t_df[['Sex','Fare']].groupby('Sex').mean()#Average fare for male and female passengers

             Fare
Sex
female  44.479818
male    25.523893

In [47]:
t_df.groupby('Survived').mean()

          PassengerId    Pclass        Age     SibSp     Parch       Fare
Survived
0          447.016393  2.531876  30.626179  0.553734  0.329690  22.117887
1          444.368421  1.950292  28.343690  0.473684  0.464912  48.395408

In [48]:
t_df.groupby('Embarked')['Survived'].count()

Embarked
C    168
Q     77
S    644
Name: Survived, dtype: int64

In [49]:
t_df.groupby('Embarked')['Age'].agg(['count','mean','min','max'])

          count       mean   min   max
Embarked
C           130  30.814769  0.42  71.0
Q            28  28.089286  2.00  70.5
S           554  29.445397  0.67  80.0